version: '3.5'

services:
  axon:
    image: 'axoniq/axonserver:4.2.4-jdk11'
    ports:
      - '8024:8024'
      - '8124:8124'
    volumes:
      - /home/users/mkociszewski/Pobrane/magisterka/axonserver/data:/data
      - /home/users/mkociszewski/Pobrane/magisterka/axonserver/events:/eventdata
      - /home/users/mkociszewski/Pobrane/magisterka/axonserver/config:/config:ro
